spring:
  application:
    name: retail

  datasource:
    url: jdbc:postgresql://localhost:5432/retail
    username: <secret>
    password: <secret>
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none